export const STORE_TYPE_APP_LOGIN = 'APP_LOGIN';
export const STORE_TYPE_APP_LOGOUT = 'APP_LOGOUT';
export const STORE_TYPE_APP_STATE = 'APP_STATE';
export const STORE_TYPE_APP_MODULE = 'APP_MODULE';
export const STORE_TYPE_APP_FLUSH_CACHE = 'APP_FLUSH_CACHE';
export const STORE_TYPE_APP_LOCK_ACCOUNT = 'APP_LOCK_ACCOUNT';
export const STORE_TYPE_APP_XSRF_TOKEN = 'XSRF_TOKEN_SAUKI_SHOP';
