const button = [
    {
        property: 'children',
        type: 'node',
        default: '-',
        required: 'true',
        description: '-',
    },
    {
        property: 'loadingButton',
        type: 'bool',
        default: 'false',
        required: 'false',
        description: '-',
    },
    {
        property: 'loadingProcess',
        type: 'bool',
        default: 'false',
        required: 'false',
        description: '-',
    },
    {
        property: 'loadingPosition',
        type: "'start', 'end', 'center'",
        default: 'start',
        required: 'false',
        description: '-',
    },
    {
        property: 'type',
        type: 'string',
        default: 'button',
        required: 'false',
        description: '-',
    },
    {
        property: 'color',
        type: "'inherit', 'primary', 'secondary', 'success', 'error', 'info', 'warning'",
        default: "'secondary'",
        required: 'false',
        description: '-',
    },
    {
        property: 'disableElevation',
        type: 'bool',
        default: 'true',
        required: 'false',
        description: '-',
    },
    {
        property: 'variant',
        type: "'contained', 'outlined', 'text'",
        default: "'contained'",
        required: 'false',
        description: '-',
    },
    {
        property: 'size',
        type: "'small', 'medium', 'large'",
        default: 'small',
        required: 'false',
        description: '-',
    },
    {
        property: 'fullWidth',
        type: 'bool',
        default: 'true',
        required: 'false',
        description: '-',
    },
    {
        property: 'disabled',
        type: 'bool',
        default: 'false',
        required: 'false',
        description: '-',
    },
    {
        property: 'startIcon',
        type: 'node',
        default: '-',
        required: 'false',
        description: '-',
    },
    {
        property: 'onClick',
        type: 'func',
        default: '-',
        required: 'false',
        description: '-',
    },
    {
        property: 'sx',
        type: 'object',
        default: '-',
        required: 'false',
        description: '-',
    },
];

export default button;
